clear paramsAll;

clear params;
params.Gridjob.runLocal = false;
params.Gridjob.requiremf = 5000;
params.Gridjob.jobname = 'layer2InitPhaseAfterWhitening';
params.Gridjob.wc_host = '';
params.ApplyWeights.inActFolder = '../../20130726_Paper/Autoencoder/layer1ActRectified';
params.ApplyWeights.inActFilenames = 'act1.mat';
params.ApplyWeights.inPhaseFolder = '../../20130726_Paper/Autoencoder/img50PhaseManySamplesFDR0p05maxdx32SmallDt';
params.ApplyWeights.inPhaseFilenames = 'phaseIter30.mat';
params.ApplyWeights.fileid = num2cell(1:50);
params.ApplyWeights.outActFolder = [];
params.ApplyWeights.outPhaseFolder = 'layer2InitPhaseAfterWhitening'; %relative to the workpath
params.ApplyWeights.weightsFile = '../NoPhaseFromLayer1/layer1ActRectifiedWhiteningWeights/weights.mat';
params.ApplyWeights.convType = 'same';
paramsAll{1} = params;

clear params;
params.Gridjob.runLocal = false;
params.Gridjob.requiremf = 12000;
params.Gridjob.jobname = 'layer2InitPhaseAfterAE';
params.ApplyWeights.inActFolder = '../NoPhaseFromLayer1/layer1ActRectifiedWhite';
params.ApplyWeights.inActFilenames = 'act.*.mat';
params.ApplyWeights.inPhaseFolder = 'layer2InitPhaseAfterWhitening'; %relative to the workpath
params.ApplyWeights.inPhaseFilenames = 'phaseIter30.mat';
params.ApplyWeights.fileid = num2cell(1:50);
params.ApplyWeights.outActFolder = [];
params.ApplyWeights.outPhaseFolder = 'layer2InitPhaseAfterAE'; %relative to the workpath
params.ApplyWeights.weightsFile = '../NoPhaseFromLayer1/layer2AE100weights/2/forwConn.mat';
params.ApplyWeights.convType = 'same';
params.ApplyWeights.b = zeros(1,1,100); %delete AE bias for phase propagation
params.ApplyWeights.actFcn = @(x) x; %delete AE activation function for phase propagation
paramsAll{2} = params;

clear params;
params.Gridjob.runLocal = false;
params.Gridjob.requiremf = 4000;
params.Gridjob.jobname = 'layer2Phase';
params.PhaseSimulation.inActFolder = '../NoPhaseFromLayer1/layer2ActRectified';
params.PhaseSimulation.inActFilenames = 'act.*.mat';
params.PhaseSimulation.inPhaseFolder = 'layer2InitPhaseAfterAE';
params.PhaseSimulation.inPhaseFilenames = 'phaseIter30.mat';
params.PhaseSimulation.inFileid = num2cell(1:50);
params.PhaseSimulation.inCellid = 1;
params.PhaseSimulation.inConnFilename = '../NoPhaseFromLayer1/layer2Conn/weights.mat';
params.PhaseSimulation.inPhaseFilename = [];
params.PhaseSimulation.outPhaseFolder = 'layer2Phase';
params.PhaseSimulation.noiseLevel = 0;
params.PhaseSimulation.noiseEMAconst = 0;
params.PhaseSimulation.tmax = 30;
params.PhaseSimulation.dt = 1;
params.PhaseSimulation.fixedPhaseDelay = 0;
params.PhaseSimulation.odeSolver = 'ode4';
params.PhaseSimulation.weightAll = 3;
params.PhaseSimulation.weightInh = 1;
params.PhaseSimulation.weightExc = 1;
params.PhaseSimulation.saveintervalPhase = 5;
params.PhaseSimulation.saveintervalMeanPhase = 5;
params.PhaseSimulation.saveintervalMeanWeightedPhase = 5;
params.PhaseSimulation.plotPhase = false;
params.PhaseSimulation.maxdphase = 2*pi/4;
paramsAll{3} = params;

clear params;
params.Gridjob.runLocal = false;
params.Gridjob.requiremf = 2000;
params.Gridjob.jobname = 'segEval';
params.Gridjob.combParallel = true;
params.SegmentationEval.inActFolder = '../NoPhaseFromLayer1/layer2ActRectified';
params.SegmentationEval.inActFilenames = 'act1.mat';
params.SegmentationEval.inPhaseFolder = 'layer2Phase';
params.SegmentationEval.outSegEvalFolder = 'segEval';
params.SegmentationEval.catName = '05june05_static_street_boston';
params.SegmentationEval.fileid = [1:50];
params.SegmentationEval.segSizeBinEdges = [exp(0:11)];
params.SegmentationEval.minPixelPerSeg = 1;
params.SegmentationEval.maxPixelPerSeg = Inf;
params.SegmentationEval.borderSize=0;
params.SegmentationEval.numPairs=10000;
params.SegmentationEval.numSubpop=100;
params.SegmentationEval.numSamplesInSubpop=1000;
params.SegmentationEval.phasePerPixel=false;
params.SegmentationEval.time={0,5,10,15,20,25,30};
params.SegmentationEval.initRandstream = true;
params.SegmentationEval.pairOnlyWithOneNonmatching = true;
params.SegmentationEval.verboseLevel = 0;
params.SegmentationEval.simOtherVarParam = [];
params.SegmentationEval.skipMissingImg = false;
params.SegmentationEval.borderEvalNumPerImg = 100;
params.SegmentationEval.borderEvalNghSize = 10;
params.SegmentationEval.borderAngleSigma = 3;
params.SegmentationEval.borderAngleUseActivityWeighting = false;
params.SegmentationEval.borderSyncUseActivityWeighting = true;
params.SegmentationEval.useHueInsteadPhase = false;
params.SegmentationEval.resizeToX = 200;
params.SegmentationEval.resizeToY = 150;
params.SegmentationEval.cropX = [];
params.SegmentationEval.cropY = [];
params.SegmentationEval.doCalcSegSync = true;
params.SegmentationEval.doCalcBorderSync = true;
params.SegmentationEval.doCalcBorderAngle = true;
paramsAll{4} = params;

clear params;
params.Gridjob.runLocal = false;
params.Gridjob.requiremf = 2000;
params.Gridjob.jobname = 'segEvalOnlyBorder';
params.Gridjob.combParallel = true;
params.Gridjob.wc_host = '';
params.SegmentationEval.inActFolder = '../NoPhaseFromLayer1/layer2ActRectified';
params.SegmentationEval.inActFilenames = 'act1.mat';
params.SegmentationEval.inPhaseFolder = 'layer2Phase';
params.SegmentationEval.outSegEvalFolder = 'segEvalOnlyBorder';
params.SegmentationEval.catName = '05june05_static_street_boston';
params.SegmentationEval.fileid = [1:50];
params.SegmentationEval.segSizeBinEdges = [exp(0:11)];
params.SegmentationEval.minPixelPerSeg = 36;
params.SegmentationEval.maxPixelPerSeg = 15000;
params.SegmentationEval.borderSize=0;
params.SegmentationEval.numPairs=10000;
params.SegmentationEval.numSubpop=100;
params.SegmentationEval.numSamplesInSubpop=1000;
params.SegmentationEval.phasePerPixel=false;
params.SegmentationEval.time={0,5,10,15,20,25,30};
params.SegmentationEval.initRandstream = true;
params.SegmentationEval.pairOnlyWithOneNonmatching = true;
params.SegmentationEval.verboseLevel = 0;
params.SegmentationEval.simOtherVarParam = [];
params.SegmentationEval.skipMissingImg = false;
params.SegmentationEval.borderEvalNumPerImg = 100;
params.SegmentationEval.borderEvalNghSize = 10;
params.SegmentationEval.borderAngleSigma = 3;
params.SegmentationEval.borderAngleUseActivityWeighting = false;
params.SegmentationEval.borderSyncUseActivityWeighting = true;
params.SegmentationEval.useHueInsteadPhase = false;
params.SegmentationEval.resizeToX = 200;
params.SegmentationEval.resizeToY = 150;
params.SegmentationEval.cropX = [];
params.SegmentationEval.cropY = [];
params.SegmentationEval.doCalcSegSync = false;
params.SegmentationEval.doCalcBorderSync = true;
params.SegmentationEval.doCalcBorderAngle = true;
paramsAll{5} = params;

clear params;
gridjobs = Gridjob(paramsAll(5));
start(gridjobs);


