clear params;
params.Gridjob.runLocal = false;
params.Gridjob.requiremf = 4000;
params.Gridjob.jobname = 'lMLayer1EvalSeveralNghSize';
params.Gridjob.combParallel = false;
params.SegmentationEval.inActFolder = 'labelMeActLayer1';
params.SegmentationEval.inActFilenames = 'act1.mat';
params.SegmentationEval.inPhaseFolder = 'labelMeLayer1PhaseAll';
params.SegmentationEval.outSegEvalFolder = 'labelMeLayer1SegEvalSeveralNghSize';
params.SegmentationEval.catName = '05june05_static_street_boston';
params.SegmentationEval.fileid = 1:50;
params.SegmentationEval.minPixelPerSeg = 50;
params.SegmentationEval.maxPixelPerSeg = Inf;
params.SegmentationEval.borderSize=0;
params.SegmentationEval.numPairs=10000; % set numPairs=0 to calc only probSegSync
params.SegmentationEval.numSubpop=100;
params.SegmentationEval.numSamplesInSubpop=1000;
params.SegmentationEval.phasePerPixel=false;
params.SegmentationEval.time=20;
params.SegmentationEval.initRandstream = true;
params.SegmentationEval.pairOnlyWithOneNonmatching = true;
params.SegmentationEval.verboseLevel = 0;
params.SegmentationEval.simOtherVarParam = [];
params.SegmentationEval.skipMissingImg = false;
params.SegmentationEval.borderEvalNumPerImg = 100;
params.SegmentationEval.borderEvalNghSize = {5,10,15};
params.SegmentationEval.borderAngleSigma = {2,3,5};
params.SegmentationEval.borderAngleUseActivityWeighting = true;
params.SegmentationEval.borderSyncUseActivityWeighting = true;
params.SegmentationEval.useHueInsteadPhase = false;
params.SegmentationEval.resizeToX = 400;
params.SegmentationEval.resizeToY = 300;
params.SegmentationEval.cropX = [];
params.SegmentationEval.cropY = [];
params.SegmentationEval.doCalcSegSync = false;
params.SegmentationEval.doCalcBorderSync = true;
params.SegmentationEval.doCalcBorderAngle = true;

gridjobs = Gridjob(params);
start(gridjobs);
